# Site settings
title: Armend Murtishi - Game Developer
description: "Armend Murtishi - Game Developer since 2015"
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "armend.cc" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https:yourusername.githu.io'

# User settings
username: Armend
user_title: Armend
email: armend@armend.cc
twitter_username: bigfatman17
github_username:  bigfatman17
gplus_username:  bigfatman17
disqus_username: bigfatman17

# Build settings
markdown: kramdown
highlighter: rouge
#permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# projects in header index
projects:
  - name: maze3d
    url: https://github.com/bigfatman17/maze3d
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules', 'tags']
